### ISSUE TITLE
StatisticEffectData Extensions Bug: unintended Float_Add stat changes stacking

### ISSUE THREAD

**Issue by korgano** [BattletechModders/Abilifier#12]
I've discovered an odd bug with the StatisticEffectData extension. I've been trying to create an ability that gives weapons with the component tags `range_verylong` or `range_extreme` structure damage via Float_Add.

Having two separate code blocks, one for each range, leads to weapons with the `range_extreme` tag having **double** the intended float amount. (For example, the intended 5 structure damage is now 10.)

Having one code block for `range_verylong` only adds structure damage to weapons with that tag. `range_extreme` weapons do not have any structure damage added to them.

Having one code block with a status effect that applies to both tags **also** doubles the intended float amount on `range_extreme` weapons.

I am not sure why this happening, because every weapon only has one range tag and the range tags have no statistical values attached, so it should only be applying the float once.

Example Code:
```
{
            "Description" : {
                "Id" : "StatusEffect-LongestRanges",
                "Name" : "ARMOR BYPASS",
                "Details" : "Very long and extreme range weapons bypass armor and deal structure damage to the target."
            },
            "effectType" : "StatisticEffect",
            "nature" : "Buff",
            "durationData" : {
                "duration" : -1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInTargetPreview" : false,
                "showInStatusPanel" : false,
                "hideApplicationFloatie" : false
            },
            "statisticData" : {
                "statName" : "StructureDamagePerShot",
                "operation" : "Float_Add",
                "modValue" : "5",
                "modType" : "System.Single",
                "targetCollection" : "Weapon"
            }
        }
```

```
"StatusEffect-LongestRanges": {
		"TargetComponentTagMatch": [
			"range_very-long",
			"range_extreme"
		]
	},
```

**Comment by ajkroeg** [comment]
@korgano I just tested and cannot replicate. Using this setup for EffectDataExtensions:
```
{
	"StatusEffect-LongestRanges": {
		"TargetComponentTagMatch": [
			"range_very-long",
			"range_extreme"
		]
	}
}
```
and a single EffectData block within an activated ability like this:
```
{
            "Description" : {
                "Id" : "StatusEffect-LongestRanges",
                "Name" : "ARMOR BYPASS",
                "Details" : "Very long and extreme range weapons bypass armor and deal structure damage to the target."
            },
            "effectType" : "StatisticEffect",
            "nature" : "Buff",
            "durationData" : {
                "duration" : -1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInTargetPreview" : false,
                "showInStatusPanel" : false,
                "hideApplicationFloatie" : false
            },
            "statisticData" : {
                "statName" : "StructureDamagePerShot",
                "operation" : "Float_Add",
                "modValue" : "5",
                "modType" : "System.Single",
                "targetCollection" : "Weapon"
            }
        }
```

I checked using a stock AC5 (which has `range_very-long`) and a stock AC2 (`range_extreme`), and both weapons did the specified 5 structure damage per shot. Note that a weapon which has more than 1 shot, i.e `"ShotsWhenFired" : 2,` would then do 10 total structure damage; 5 for each shot, and that any damage added by StructureDamagePerShot is still subject to any damage modifiers such as cover, braced, etc., and obviously using the `Float_Add` operation means it will stack with any direct structure damage inherent to the weapon itself (such as the vanilla gauss rifle).

However, I strongly suspect the real issue is that your effectData has no stacklimit and a duration of -1. This means that every time the ability is activated, it will add 5 structure damage to the affected weapons. On the first activation, it would do 5 damage. Then if you activate the ability again it would do 10, then 15, and so on.
